spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.102.136/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  #在全局配置中当返回的值为null时则不返回
  jackson:
    default-property-inclusion: non_null
#logging:
#  pattern:
#    console: "%d - %msg%n"
#    path: /var/log/tomcat/
#    file: /var/log/tomcat/sell.log
#    level:

#项目名    -- 项目的前缀
server:
  context-path: /sell
#      com.hhsth.shelldemo.LoggerTest: debug
wechat:
  mpAppId: wxdcxxxxxxxxx
  mpAppSecret: xxxxxxxxx
  mchId: xxxxxxxxx
  mchKey:xxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: xxxxxxxxx/sell/pay/notify